[workspace]
members = [
    "ractor",
    "ractor_cluster",
    "ractor_cluster_derive",
    "ractor_playground",
    "ractor_cluster_integration_tests",
    "ractor_example_entry_proc",
    "xtask", 
    "ractor_async_trait_decl",
]
resolver = "2"
