name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    name: ${{matrix.name}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Run the default tests
            package: ractor
            # flags:
          - name: Test ractor with async-trait
            package: ractor
            flags: -F async-trait
          - name: Test ractor without span propogation
            package: ractor
            flags: --no-default-features -F tokio_runtime
          - name: Test ractor with the `cluster` feature
            package: ractor
            flags: -F cluster
          - name: Test ractor with the `blanket_serde` feature
            package: ractor
            flags: -F blanket_serde
          - name: Test ractor with async-std runtime
            package: ractor
            flags: --no-default-features -F async-std,message_span_propogation
          - name: Test ractor with async-std runtime but no span propagation
            package: ractor
            flags: --no-default-features -F async-std
          - name: Test ractor with async-std runtime and async-trait
            package: ractor
            flags: --no-default-features -F async-std,async-trait
          - name: Test ractor_cluster with native async traits
            package: ractor_cluster
            # flags:
          - name: Test ractor_cluster with async_trait
            package: ractor_cluster
            flags: -F async-trait
          - name: Test ractor with the monitor API
            package: ractor
            flags: -F monitors

    steps:
      - uses: actions/checkout@main

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: ${{matrix.name}}
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --package ${{matrix.package}} ${{matrix.flags}}

      - name: Test everything
        uses: actions-rs/cargo@v1
        with:
          command: test

  clippy:
    name: Clippy (All Crates)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install minimal stable with clippy
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true

      - name: Run Clippy on all crates
        run: .github/workflows/clippy_all.sh

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install minimal stable with rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
          override: true

      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install minimal stable with rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
          override: true

      - name: Run cargo doc on release profile
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --lib -r

  benches:
    name: benches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Compile benchmarks
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --no-run
